config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  resources :questions do
    resources :answers
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :name, presence: true
	validates :content, presence: true, length: { maximum: 65_535 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answers, dependent: :destroy
	belongs_to :user
	validates :name, presence: true
	validates :content, presence: true, length: { maximum: 65_535 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :answers, dependent: :destroy
  has_many :questions, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :email, presence: true
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }

  def own?(object)
    id == object.user_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answers, only: %i[edit update destroy]

  def create 
    @question = Question.find(params[:question_id])
    @answer = current_user.answers.build(answer_params)
    if @answer.save
      redirect_to question_path(@question), success: t('defaults.message.created', item: Answer.model_name.human)
    else
      redirect_to question_path(@question), danger: t('defaults.message.not_created', item: Answer.model_name.human)
    end
  end

  def edit;end

  def update
    if @answer.update(answer_params)
      redirect_to question_path(@question), success: t('defaults.message.updated', item: Answer.model_name.human)
    else
      flash[:danger] = t('defaults.message.not_updated', item: Answer.model_name.human)
      render :edit
    end
  end

  def destroy
    @answer.destroy!
    redirect_to question_path(@question), success: t('defaults.message.deleted', item: Answer.model_name.human)
  end

  private

  def answer_params
    params.require(:answer).permit(:name, :content, :question_id)
  end

  def set_answers
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:question_id])
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger

  before_action :require_login
  
  private

  def not_authenticated
    flash[:warning] = t('defaults.message.require_login')
    redirect_to login_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :require_login, only: %i[index show]
  before_action :set_question, only: %i[edit show update destroy]
  
  def index
    @questions = Question.all.includes(:user).order(created_at: :desc).page(params[:page])
  end

  def show
    @answer = Answer.new
    @answers = @question.answers.includes(:question).order(created_at: :desc).page(params[:page])
  end

  def edit;end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      redirect_to questions_path, success: t('defaults.message.created', item: Question.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_created', item: Question.model_name.human)
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to questions_path, success: t('defaults.message.updated', item: Question.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: Question.model_name.human)
      render :edit
    end
  end

  def destroy
    @question.destroy!
    redirect_to questions_path(@question), success: t('defaults.message.deleted', item: Question.model_name.human)
  end

  private

  def question_params
    params.require(:question).permit(:name, :content)
  end
  
  def set_question
    @question = Question.find(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top]

  def top;end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to questions_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new
    @user = User.new
  end
    
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end
    
  private
    
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :last_name, :first_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '')
    base_title = 'RUNTEQ Q&A'

    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end

  def flash_class_for(key)
    case key
      when 'success' then 'alert-success'
      when 'failed'   then 'alert-danger'
    end
  end
end

app/views/answers/_answer.html.slim
tr
  td.w-auto
    = answer.name
  td.w-50
    = answer.content
  td.w-auto
    = l answer.created_at, format: :short
  td.w-auto
    - if current_user&.own?(answer)
      = link_to t('defaults.edit'), edit_question_answer_path(@question, answer), class: 'btn btn-warning'
      = link_to t('defaults.delete'), question_answer_path(@question, answer), class: 'btn btn-warning', method: :delete, data: { confirm: t('defaults.message.delete_confirm') }

app/views/answers/_answers.html.slim
= render answers

app/views/answers/_form.html.slim
= form_with model: [question, answer], local: true do |f|
  = render 'shared/error_messages', object: f.object
  = f.hidden_field :question_id, { value: question.id}
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control'
  .text-center
    = f.submit t('defaults.post'), class: 'btn btn-warning'

app/views/answers/edit.html.slim
- content_for(:title, t('.title'))
div
  h2.mt-5
    = t('.title')
  h2
    |  　
    = render 'form', { question: @question, answer: @answer }

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = page_title(yield(:title))
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.png'
  body
    - if logged_in?
      = render 'shared/header'
    - else
      = render 'shared/before_login_header'
    = render 'shared/flash_message', flash: flash
    .container
      = yield

app/views/questions/_form.html.slim
= form_with model: question, local: true do |f|
  = render 'shared/error_messages', object: f.object
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control'
  .text-center
    = f.submit t('defaults.post'), class: 'btn btn-warning'

app/views/questions/_question.html.slim
tr
  td.w-50
    = link_to question.content, question_path(question), class: 'question-font-size text-dark'
  td.w-auto
    = question.name
  td.w-auto
    = l question.created_at, format: :short
  td.w-auto
    - if current_user&.own?(question)
      = link_to t('defaults.edit'), edit_question_path(question), class: 'btn btn-warning'
      = link_to t('defaults.delete'), question_path(question), class: 'btn btn-warning', method: :delete, data: { confirm: t('defaults.message.delete_confirm') }

app/views/questions/edit.html.slim
- content_for(:title, t('.title'))
div
  .col-md-4.offset-md-4.mt-5
    h2.text-center
      | 質問の編集
    = render 'form', { question: @question }

app/views/questions/index.html.slim
- content_for(:title, t('.title'))
h2.mt-5.mb-5.text-center
  = t('.title')
  h2
    = link_to t('.question'), new_question_path, class: 'btn btn-warning d-block mx-auto w-25 mb-5'
    .row
      .col-md-12
        table.table.table-striped.text-size
          thead.thead-light
            tr
              th.w-50
                = t('defaults.question')
              th.w-auto
                = t('defaults.name')
              th.w-auto
                = t('defaults.created_at')
              th

            tr

          tbody
            = render @questions
        = paginate @questions

app/views/questions/new.html.slim
- content_for(:title, t('.title'))
div
  .col-md-4.offset-md-4.mt-5
    h2.text-center
      = t('.title')
    = render 'form', { question: @question}

app/views/questions/show.html.slim
- content_for(:title, t('.title'))
.row
  .col-md-12.mt-5
    h2
      = @question.content
    div
      = t('.from')
      = @question.name
    hr
    div
      h3
        = t('.title')
      table.table.table-striped
        - if @question.answers.any?
          thead.thead-light
            tr
              td.w-auto
                = t('.name')
              td.w-50
                = t('.answer')
              td.w-auto
                | 作成日
              td.w-auto
            tr

          tbody
            = render 'answers/answers', { answers: @answers }
        - else
          p
            = t('.no_answer')
      = paginate @answers
      h3
        = t('.answer_post')
      = render 'answers/form', { answer: @answer, question: @question }

app/views/shared/_before_login_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse.bg-warning
  .container
    = link_to t('defaults.title'), root_path, id: 'logo', class: 'text-dark pt-2 pb-2 header-font-size'

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_messages.alert.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li
          = msg

app/views/shared/_flash_message.html.slim
    - flash.each do |key, value|
      - key = "info" if key == "notice"
      - key = "danger"  if key == "alert"
      = content_tag :div, value, class: "alert alert-#{key}"

app/views/shared/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse.bg-warning
  .container
    = link_to t('defaults.title'), root_path, id: "logo", class: "text-dark pt-2 pb-2 header-font-size"
    nav
      ul.nav.navbar-expand-md.navbar-right
        li.mr-5
          = link_to t('defaults.questions_all'), questions_path, class: 'text-dark'
        li
          = link_to t('defaults.logout'), logout_path, class: 'text-dark',method: :delete

app/views/static_pages/top.html.slim
.mx-auto[style="width: 500px;"]
  div
    h1.display-4.text-center.mt-5
      = t('.title')
    = image_tag 'situmon.png', class: 'd-block mx-auto w-50'
    p.text-center.mt-5
      | こちらはRUNTEQ生に気になる質問をして
    p.text-center.mb-5
      | 回答を共有するサービスになります！質問、回答お待ちしております！
    .text-center.d-block
      - if logged_in?

      - else
        .mb-5
          = link_to t('.questions_all'), questions_path, class: 'btn btn-warning'
        = link_to t('defaults.login'), login_path, class: 'btn btn-warning mr-3'
        = link_to t('.register_page'), new_user_path, class: 'btn btn-warning'

app/views/user_sessions/new.html.slim
- content_for(:title, t('.title'))
.container
  .row
    .col-md-10.offset-md-1.col-lg-8.offset-lg-2.mt-5
      h1
        = t('.title')
      = form_with url: login_path, local: true do |f|
        .form-group
          = f.label :email, User.human_attribute_name(:email)
          = f.text_field :email, class: 'form-control'
        .form-group
          = f.label :password, User.human_attribute_name(:password)
          = f.password_field :password, class: 'form-control'
        .actions
          = f.submit t('defaults.login'), class: 'btn btn-warning'
      .text-center
        = link_to t('.to_register_page'), new_user_path, class: 'text-dark'

app/views/users/new.html.slim
- content_for(:title, t('.title'))
.container
  .row
    .col-md-10.offset-md-1.col-lg-8.offset-lg-2.mt-5
      h1
        | ユーザー登録
      = form_with model: @user, local: true do |f|
        = render 'shared/error_messages', object: f.object
        .form-group
          = f.label :last_name
          = f.text_field :last_name, class: 'form-control'
        .form-group
          = f.label :first_name
          = f.text_field :first_name, class: 'form-control'
        .form-group
          = f.label :email
          = f.email_field :email, class: 'form-control'
        .form-group
          = f.label :password
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :password_confirmation
          = f.password_field :password_confirmation, class: 'form-control'
        = f.submit '登録', class: 'btn btn-warning'
      .text-center
        = link_to 'ログインページへ', login_path, class: 'text-dark'